#cloud-config
# vim:syntax=yaml
debug: True
ssh_pwauth: True
disable_root: false
chpasswd:
  list: |
    root:123456789
    centos:123456789
  expire: false
runcmd:
- sed -i'.orig' -e's/without-password/yes/' /etc/ssh/sshd_config
- service sshd restart
- mkdir /home/centos/data
- [ sh, -xc, "curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh"]
- [ sh, -xc, "mkfs.ext4 /dev/xvdh; chown 'centos' /home/centos/data; echo '/dev/xvdh /home/centos/data ext4 defaults,nofail,noatime,nodiratime,barrier=0,data=writeback 0 2' >> /etc/fstab; mount -a"]